[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyB4oHOXnYgshaZr183gWPha6EYMuuoZV6Q"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
